- hosts: all
  become: true
  tasks:
   - name: Log into DockerHub
     docker_login:
      username: 
      password: 
      email:  
      
   - name: Pull image from docker hub
     command: docker pull rchandu3447/chandu-python:"{{buildNumber}}"

   - name: Stop current running container
     command: docker stop chandu-c1
     ignore_errors: yes

   - name: Remove stopped container
     command: docker rm chandu-c1
     ignore_errors: yes

   - name: Run a container from the pulled image
     command: docker run --name chandu-c1 --network host -d rchandu3447/chandu-c1:"{{buildNumber}}"
